# ===============================
# Server Configuration
# ===============================
server.port=8081

# ===============================
# Spring Application
# ===============================
spring.application.name=employee-service

# ===============================
# Database Configuration (Kubernetes)
# ===============================
#spring.datasource.url=jdbc:mysql://mysql:3306/employee_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# Database Configuration (Local)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/employee_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Ashu@tosh0407
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Actuator (REQUIRED for K8s probes)
# ===============================
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

# ===============================
# Custom App Properties
# ===============================
app.message=Running in Dev Environment